# Generated by Django 3.1.7 on 2021-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('contactAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
